export const STATS = {
    Kanye: {
        displayName: 'Kanye West',
        color: '#0551B4',
        sentences: [
            "All you have to be is yourself",
            "Believe in your flyness...conquer your shyness.",
            "Burn that excel spread sheet",
            "Decentralize",
            "Distraction is the enemy of vision",
            "Everything you do in life stems from either fear or love",
            "For me giving up is way harder than trying.",
            "For me, money is not my definition of success. Inspiring people is a definition of success",
            "Fur pillows are hard to actually sleep on",
            "George Bush doesn't care about black people",
            "Have you ever thought you were in love with someone but then realized you were just staring in a mirror for 20 minutes?",
            "I care. I care about everything. Sometimes not giving a f#%k is caring the most.",
            "I feel calm but energized",
            "I feel like I'm too busy writing history to read it.",
            "I feel like me and Taylor might still have sex",
            "I give up drinking every week",
            "I leave my emojis bart Simpson color",
            "I love sleep; it's my favorite.",
            "I make awesome decisions in bike stores!!!",
            "I really love my Tesla. I'm in the future. Thank you Elon.",
            "I still think I am the greatest.",
            "I think I do myself a disservice by comparing myself to Steve Jobs and Walt Disney and human beings that we've seen before. It should be more like Willy Wonka...and welcome to my chocolate factory.",
            "I want the world to be better! All I want is positive! All I want is dopeness!",
            "I wish I had a friend like me",
            "I'd like to meet with Tim Cook. I got some ideas",
            "I'll say things that are serious and put them in a joke form so people can enjoy them. We laugh to keep from crying.",
            "I'm a creative genius",
            "I'm nice at ping pong",
            "I'm the best",
            "If I don't scream, if I don't say something then no one's going to say anything.",
            "If I got any cooler I would freeze to death",
            "If you have the opportunity to play this game of life you need to appreciate every moment. a lot of people don't appreciate the moment until it's passed.",
            "Just stop lying about shit. Just stop lying.",
            "Keep squares out yo circle",
            "Keep your nose out the sky, keep your heart to god, and keep your face to the rising sun.",
            "Let's be like water",
            "Man... whatever happened to my antique fish tank?",
            "My dad got me a drone for Christmas",
            "My greatest award is what I'm about to do.",
            "My greatest pain in life is that I will never be able to see myself perform live.",
            "One day I'm gon' marry a porn star",
            "One of my favorite of many things about what the Trump hat represents to me is that people can't tell me what to do because I'm black",
            "Only free thinkers",
            "People always say that you can't please everybody. I think that's a cop-out. Why not attempt it? Cause think of all the people that you will please if you try.",
            "People always tell you 'Be humble. Be humble.' When was the last time someone told you to be amazing? Be great! Be awesome! Be awesome!",
            "People only get jealous when they care.",
            "Perhaps I should have been more like water today",
            "Pulling up in the may bike",
            "Shut the fuck up I will fucking laser you with alien fucking eyes and explode your fucking head",
            "Sometimes I push the door close button on people running towards the elevator. I just need my own elevator sometimes. My sanctuary.",
            "Sometimes you have to get rid of everything",
            "Style is genderless",
            "The thought police want to suppress freedom of thought",
            "The world is our family",
            "The world is our office",
            "Today is the best day ever and tomorrow's going to be even better",
            "Truth is my goal. Controversy is my gym. I'll do a hundred reps of controversy for a 6 pack of truth",
            "Tweeting is legal and also therapeutic",
            "We all self-conscious. I'm just the first to admit it.",
            "We came into a broken world. And we're the cleanup crew.",
            "You can't look at a glass half full or empty if it's overflowing.",
            "I hate when I'm on a flight and I wake up with a water bottle next to me like oh great now I gotta be responsible for this water bottle",
            "All the musicians will be free",
            "Artists are founders",
            "Buy property",
            "Culture is the most powerful force in humanity under God",
            "Empathy is the glue",
            "I am one of the most famous people on the planet",
            "I am running for President of the United States",
            "I am the head of Adidas. I will bring Adidas and Puma back together and bring me and jay back together",
            "I am Warhol. I am the No. 1 most impactful artist of our generation. I am Shakespeare in the flesh.",
            "I channel Will Ferrell when I'm at the daddy daughter dances",
            "I don't wanna see no woke tweets or hear no woke raps ... it's show time ... it's a whole different energy right now",
            "I hear people say this person is cool and this person is not cool. People are cool. Man has never invented anything as awesome as a an actual person but sometimes we value the objects we create over life itself",
            "I honestly need all my Royeres to be museum quality... if I see a fake Royere Ima have to Rick James your couch",
            "I love UZI. I be saying the same thing about Steve Jobs. I be feeling just like UZI",
            "I need an army of angels to cover me while I pull this sword out of the stone",
            "I spoke to Dave Chapelle for two hours this morning. He is our modern day Socrates",
            "I was just speaking with someone that told me their life story and they used to be homeless.",
            "I watch Bladerunner on repeat",
            "I'm giving all Good music artists back the 50% share I have of their masters",
            "I'm going to personally see to it that Taylor Swift gets her masters back. Scooter is a close family friend",
            "I'm the new Moses",
            "Life is the ultimate gift",
            "Ma$e is one of my favorite rappers and I based a lot of my flows off of him",
            "Manga all day",
            "My first pillar when I'm on the board of adidas will be an adidas Nike collaboration to support community growth",
            "My mama was a' English teacher. I know how to use correct English but sometimes I just don't feel like it aaaand I ain't got to",
            "My memories are from the future",
            "My mother in law Kris Jenner ... makes the best music playlist",
            "People say it's enough and I got my point across ... the point isn't across until we cross the point",
            "People tried to talk me out of running for President. Never let weak controlling people kill your spirit",
            "So many of us need so much less than we have especially when so many of us are in need",
            "Speak God's truth to power",
            "The media tries to kill our heroes one at a time",
            "The world needs more Joy... this idea is super fresh",
            "There are 5 main pillars in a professional musicians business - Recording, Publishing, Touring, Merchandise & Name and likeness",
            "There are people sleeping in parking lots",
            "There's a crying need for civility across the board. We need to and will come together in the name of Jesus.",
            "There's so many lonely emojis man",
            "Trust me ... I won't stop",
            "Two years ago we had 50 million people subscribed to music streaming services around the world. Today we have 400 million.",
            "We are here to complete the revolution. We are building the future",
            "We as a people will heal. We will insure the well being of each other",
            "We have to evolve",
            "We must and will cure homelessness and hunger. We have the capability as a species",
            "We must form a union. We must unify",
            "We used to diss Michael Jackson the media made us call him crazy ... then they killed him",
            "We will be recognized",
            "We will change the paradigm",
            "We will cure hunger",
            "We will heal. We will cure.",
            "We're going to move the entire music industry into the 21st Century",
            "We've gotten comfortable with not having what we deserve",
            "Who made up the term major label in the first place???",
            "Winning is the only option",
            "For me to say I wasn't a genius I'd just be lying to you and to myself",
            "I've known my mom since I was zero years old. She is quite dope.",
            "I don't expect to be understood at all.",
            "I'm on the pursuit of awesomeness, excellence is the bare minimum.",
            "You basically can say anything to someone on an email or text as long as you put LOL at the end.",
            "If you have the opportunity to play this game of life you need to appreciate every moment. A lot of people don't appreciate the moment until it's passed.",
            "Keep your nose out the sky, keep your heart to god, and keep your face to the raising sun.",
            "George Bush doesn't care about black people.",
            "I refuse to accept other people's ideas of happiness for me. As if there's a 'one size fits all' standard for happiness.",
            "I love sleep; it's my favorite.",
            "I am Warhol. I am the No. 1 most impactful artist of our generation. I am Shakespeare in the flesh.",
            "Here's something that's contrary to popular belief: I actually don't like thinking. I think people think I like to think a lot. And I don't. I do not like to think at all.",
            "They say you can rap about anything except for Jesus, that means guns, sex, lies, video tapes, but if I talk about God my record won't get played Huh?",
            "I am not a fan of books.",
            "Fashion is merely an opinion. And I've got a lot of opinions.",
            "All these walls that keep us from loving each other as one family or one race - racism, religion, where we grew up, whatever, class, socioeconomic - what makes us be so selfish and prideful, what keeps us from wanting to help the next man, what makes us be so focused on a personal legacy as opposed to the entire legacy of a race.",
            "I can analyze people's intentions. Immediately. That's just a warning. To everyone.",
            "I just want people to be the best thems and live the happiest lives possible.",
            "I ain't here to argue about his facial features. Or here to convert atheists into believers. I'm just trying to say the way school need teachers the way Kathie Lee needed Regis that's the way yall need Jesus.",
            "Man, I'm the No. 1 living and breathing rock star. I am Axl Rose; I am Jim Morrison; I am Jimi Hendrix.",
            "I'm inspired by Walt Disney. I'm inspired by Howard Hughes. I'm inspired by Henry Ford. I'm inspired by Steve Jobs. I mean, I'm inspired by James Perse.",
            "It's funny because I've made a living off of words, but words get in the way of what you really want to say",
            "There was a time Michael Jackson couldn't get his video on MTV because he was considered to be 'urban.' The Michael Jackson. So I literally have to be the Michael Jackson of apparel in order to break down the doors for everyone who will come after I'm gone, after I'm dead.",
            "I love being American, and I love family. I love having a family, and I feel so blessed, and I feel like God gave me exactly what I wanted, so now I have to do the right thing in God's eyes also. Just follow what God wants me to do.",
            "Michael Jordan changed so much in basketball, he took his power to make a difference. It's so much going on in music right now and somebody has to make a difference",
            "I think I do myself a disservice by comparing myself to Steve Jobs and Walt Disney and human beings that we've seen before. It should be more like Willy Wonka... and welcome to my chocolate factory.",
        ],
    },
    Trump: {
        displayName: 'Donald Trump',
        color: 'rgb(108, 66, 155)',
        sentences: [
            "Everything in life is luck.",
            "What separates the winners from the losers is how a person reacts to each new twist of fate.",
            "The 1990's sure aren't like the 1980's.",
            "Sometimes your best investments are the ones you don't make.",
            "Experience taught me a few things. One is to listen to your gut, no matter how good something sounds on paper. The second is that you're generally better off sticking with what you know. And the third is that sometimes your best investments are the ones you don't make.",
            "Money was never a big motivation for me, except as a way to keep score. The real excitement is playing the game.",
            "Every time you walk down the street people are screaming, 'You're fired!'",
            "I have made the tough decisions, always with an eye toward the bottom line. Perhaps it's time America was run like a business.",
            "One of the key problems today is that politics is such a disgrace, good people don't go into government.",
            "Sometimes by losing a battle you find a new way to win the war.",
            "I'm the No. 1 developer in New York, I'm the biggest in Atlantic City, and maybe we'll keep it that way.",
            "In the end, you're measured not by how much you undertake but by what you finally accomplish.",
            "Well, I am a Republican, and I would run as a Republican. And I have a lot of confidence in the Republican Party. I don't have a lot of confidence in the president. I think what's happening to this country is unbelievably bad. We're no longer a respected country.",
            "China gets their oil from Libya. Why isn't China involved? They're going out spending billions of dollars a day on trying to take over the world economically. And we're spending billions and billions and billions of dollars on policing the world. Why isn't China involved with Libya? That - we don't get oil from Libya, China does.",
            "My big focus is China and OPEC and all of these countries that are just absolutely destroying the United States.",
            "It's always good to be underestimated.",
            "But I believe in fair trade, and I will tell you, I have many, many friends heading up corporations, and people that do just business in China, they say it's virtually impossible. It's very, very hard to come into China. And yet, we welcome them with open arms.",
            "The debt limits have to come down. The whole world of debt has to be changed as far as this country is concerned. We have to create jobs and we have to create them rapidly because if we don't things are just going to head in a direction that's going to be almost impossible to recover from.",
            "I do have my ducks in line if I want to do it, but I'd love to see the Republicans pick somebody that was going to win and take over this country and frankly, to use the expression, 'Make America great again.'",
            "Mitt - what I speak to Mitt Romney about is jobs. What I speak to Mitt Romney about is China, because he's got a great view on China and how they're trying to destroy our country by taking our jobs and making our product and manipulating their currency, so that it makes it almost impossible for our companies to compete."
        ],
    },
    Ryan: {
        displayName: 'Ryan Reynolds',
        color: 'rgb(147, 5, 96)',
        sentences: [
            "When you have expectations, you are setting yourself up for disappointment.",
            "I just love bikes. It's not the safest passion to have, but I guess it's better than Russian roulette.",
            "There's a very real possibility in this industry of going out and leading your life and then going home and being a voyeur of your own life. You can literally go watch yourself - where you went last night, what you did, what the things that people presuppose about you. It's kind of crazy.",
            "Acting has given me a way to channel my angst. I feel like an overweight, pimply faced kid a lot of the time - and finding a way to access that insecurity, and put it toward something creative is incredibly rewarding. I feel very lucky.",
            "I love Canada. It makes a nice hat for America. When America runs out of water, it's the first place I'll go.",
            "I have daddy issues. So I keep tissues on me at all times.",
            "I grew up in Vancouver, British Columbia.",
            "I've had an alarming amount of concussions.",
            "I don't personally believe that villains exist. Villains are just a way of saying that somebody has an opposing conviction.",
            "I understand the climate we live in and why people are curious. But it's just tough and almost emotionally violent - for anyone, I think - to see your personal life summarized in a sentence.",
            "Marathon running, for me, was the most controlled test of mettle that I could ever think of. It's you against Darwin.",
            "We might be too proud to admit it as guys, but we still need to learn how to manage responsibility, how to face our challenges.",
            "I think a fragrance is more of a signature than even what you wear - something you'll remember more down the road than a shirt.",
            "I was a really nervous kid. I was extremely sensitive. Incredibly perceptive.",
            "When I exhale, I just turn right into Louie Anderson.",
            "Like a lot of people, I've got a self-loathing streak that's alive and well. It acts as a de facto engine when I'm working, but it also has its extraordinary pitfalls, too.",
            "It's a nice visual. I had just done Blade and I put on more weight for Blade and I thought I might as well use it so I kept it and added a little more. I wanted him to be a big bear.",
            "It was comical because you're at a firing range, all these people are so seriously shooting their little guns.",
            "Four months after we finished shooting, I'd been in New Orleans shooting another movie and my agent and I were having a bite to eat - actually in London - and he's sitting there and goes, 'Wow, I just can't believe how ripped you are.",
            "My family is as far from a stage family as you could ever possibly find.",
        ],
        
    }
}

export const CELEBRITIES = ['Kanye', 'Trump', 'Ryan'];